version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - /db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
      - redis
    build: ./
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    environment:
      - MYSQL_DATABASE_URL=$MYSQL_DATABASE_URL
      - REDIS_PORT=$REDIS_PORT
      - REDIS_HOST=$REDIS_HOST
    stdin_open: true
    tty: true
  redis:
    image: redis:alpine
